### ISSUE TITLE
Progetto abbandonato?

### ISSUE THREAD

**Issue by tassoman** [italia/design-wireframe-kit#44]
Questo progetto è abbandonato? 

Mi sembra che la parte di [progettazione e prototipazione ](https://designers.italia.it/risorse-per-progettare/progettare/prototipazione/realizza-un-prototipo-in-bassa-fedelta/)non sia tenuta molto in considerazione nel totale.

Ho provato ad aprire i progetti sketch ormai 6 di anni fa e presentano solo il lavoro svolto per la progettazione UI/UX del servizio di accesso con SPID.

Mi chiedevo se fosse più utile avere dei file separati, basati su protocollo aperto, **ad esempio in formato SVG**. 
Che seguano le [indicazioni proposte dai componenti React](https://designers.italia.it/design-system/componenti/) già pronti. 

Una specie di export o conversione da React a SVG. Affinché sia immediato importarli nei software di design, come Adobe XD, Inkscape o addirittura presentazioni ODP/PPTX.

**Comment by Fupete** [comment]
Ciao @tassoman, 

per la progettazione e prototipazione in alta fedeltà con quanto disponibile in Bootstrap Italia, o nei kit derivati per React e Angular, puoi già usare UI Kit Italia. È questo a cui ti riferisci? È la risorsa principale di design system .italia. È disponibile sia per Figma che per Sketch, seppure per quest'ultimo è un'esportazione automatica rimane abbastanza funzionale. Parti sempre dalla documentazione di design system .italia per trovare tutti i link giusti https://designers.italia.it/design-system/come-iniziare/per-designer/. UI Kit Italia è il riferimento su cui sono costruiti, issue di coerenza permettendo, tutti e tre i framework di sviluppo. Risolve i tuoi bisogni?  

Invece, per la prototipazione e progettazione a bassa o media qualità di un flusso, non hi-fi, ti confermo che al momento non è prevista l'uscita a breve di un nuovo design-wireframe-it dedicato, come quello disponibile in questa repository. Puoi comunque ancora usarlo per la mia esperienza aprendolo in Sketch o importandolo per es. in Figma, seppure ha i suoi limiti tecnologici dati dall'età. Saraebbe interessante andare verso soluzioni completamente open per le future versioni del wireframe kit, oggi che ci sono sul mercato. Su questo, ovviamente, ogni possibile proposta di contributo dalla community è benvenuta.

**Comment by tassoman** [comment]
Ciao @Fupete grazie per il chiarimento, sono riuscito ad aprire il progetto Sketch del **UI-Kit** Italia dentro Adobe XD. 
Vedo che contiene tutte le informazioni dettagliate che i Kit di sviluppo per i vari framework frontend.

Sebbene fossi un po' confuso nella richiesta precedente, sono più alla ricerca di un sistema veloce di prototipazione a bassa definizione, che sia intermedio tra il file PDF "statico" e "analogico" e maschere digitali componibili. Se riuscissi a produrre qualcosa di utile ed efficace, avrò cura di condividerlo. Nel frattempo, grazie!

**Comment by Fupete** [comment]
Bene @tassoman, grazie a te. 

ps. ad aver tempo sarebbe interessante implementare un kit wireframe lo-fi (e magari mid-fi) in [Penpot](https://penpot.app/). Di base usa tecnologia svg, non so se lo conosci, magari può interessarti.

**Comment by tassoman** [comment]
Ah caspita, esiste già! 
Grazie per il suggerimento, intendevo proprio un sistema simile, mi sarebbe bastato anche soltanto un file da usare in inkscape. 
Questa pagina di documentazione, indica come costruire delle [librerie di risorse](https://help.penpot.app/user-guide/libraries/#shared-libraries) 👀
